async (page) => {
  const errors=[];
  page.on("pageerror",e=>errors.push(e.message));
  const assert=(condition,message)=>{if(!condition)throw Error(message);};
  await page.setViewportSize({width:1440,height:1000});
  await page.getByLabel("辩题全文",{exact:false}).fill("人工智能的发展会让人类更自由 / 更不自由（界面验收）");
  await page.getByRole("button",{name:"开始备赛",exact:false}).click();
  await page.getByRole("dialog").waitFor({state:"visible"});
  await page.getByLabel("Base URL",{exact:true}).fill("https://provider.example/v1");
  await page.getByLabel("模型 ID",{exact:true}).fill("qa-model-alpha");
  await page.getByLabel("API Key",{exact:false}).fill("qa-only-test-alpha");
  await page.getByRole("button",{name:"测试连接",exact:true}).click();
  await page.getByRole("status").filter({hasText:"连接测试通过"}).waitFor();
  await page.getByRole("button",{name:"连接模型",exact:false}).click();
  await page.getByRole("dialog").waitFor({state:"hidden"});
  assert(await page.locator("#api-key").inputValue()==="","Key field not cleared");
  await page.getByRole("button",{name:"开始备赛",exact:false}).click();
  await page.locator("#step-status").filter({hasText:"等待你的判断"}).waitFor();
  assert(!await page.locator("#confirm-button").isVisible(),"Initial question bypassed");
  await page.getByLabel("回答教练或提出修改意见").fill("自由应包含实际选择机会，比较学习、工作与公共生活，注意工具和制度的区别。");
  await page.getByRole("button",{name:"发送回答",exact:true}).click();
  await page.locator("#confirm-button").waitFor({state:"visible"});
  assert(await page.locator("#document-content table").count()>0,"Markdown table missing");
  await page.screenshot({path:"output/playwright/sharing-workspace-light.png"});
  await page.locator("#confirm-button").click();
  await page.locator("#plan-box").waitFor({state:"visible"});
  assert(await page.locator("#plan-box li").count()===3,"Search plan incomplete");
  await page.locator("#confirm-button").click();
  await page.locator("#source-count").filter({hasText:"1"}).waitFor();
  await page.locator("#confirm-button").waitFor({state:"visible"});
  const sid=page.url().split("#")[1];
  await page.getByRole("button",{name:"导出档案",exact:false}).click();
  const downloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"完整 ZIP 压缩包",exact:false}).click();
  const download=await downloadEvent;
  await download.saveAs("output/playwright/sharing-qa-export.zip");
  await page.getByRole("button",{name:"关闭下载",exact:true}).click();
  await page.reload();
  await page.locator("#session-topic").filter({hasText:"界面验收"}).waitFor();
  assert(await page.locator("#model-name").textContent()==="模型已连接","Refresh lost connection");
  const noKey=await page.evaluate(()=>![...Object.values(localStorage),...Object.values(sessionStorage)].some(v=>v.includes("qa-only-test")));
  assert(noKey,"Key persisted in browser storage");
  const otherContext=await page.context().browser().newContext();
  const other=await otherContext.newPage();
  await other.goto("http://127.0.0.1:8767");
  await other.locator("#model-name").filter({hasText:"连接你的模型"}).waitFor();
  const isolation=await other.evaluate(async sid=>{
    const config=await (await fetch("/api/config")).json();
    const list=await (await fetch("/api/sessions")).json();
    const read=await fetch("/api/sessions/"+sid);
    const download=await fetch("/api/sessions/"+sid+"/download/zip");
    const action=await fetch("/api/sessions/"+sid+"/action",{method:"POST",headers:{"Content-Type":"application/json","X-Debate-Client":"workbench","X-CSRF-Token":config.csrf},body:JSON.stringify({action:"rework",revision:0,target:0})});
    return {configured:config.configured,count:list.length,read:read.status,download:download.status,action:action.status};
  },sid);
  assert(!isolation.configured&&isolation.count===0&&isolation.read===409&&isolation.download===409&&isolation.action===409,"Visitor isolation failed");
  await other.getByRole("button",{name:"模型连接",exact:false}).click();
  await other.getByLabel("Base URL",{exact:true}).fill("https://provider.example/v1");
  await other.getByLabel("模型 ID",{exact:true}).fill("qa-model-beta");
  await other.getByLabel("API Key",{exact:false}).fill("qa-only-test-beta");
  await other.getByRole("button",{name:"连接模型",exact:false}).click();
  await other.getByRole("dialog").waitFor({state:"hidden"});
  await otherContext.close();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:"output/playwright/sharing-workspace-mobile.png"});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),"Mobile overflow");
  await page.getByRole("button",{name:"模型",exact:true}).click();
  await page.getByRole("button",{name:"断开连接并暂停任务",exact:true}).click();
  await page.locator("#connection-status").filter({hasText:"尚未连接"}).waitFor();
  await page.screenshot({path:"output/playwright/sharing-settings-mobile.png"});
  await page.getByRole("button",{name:"关闭设置",exact:true}).click();
  await page.getByRole("link",{name:"工作空间",exact:true}).click();
  await page.screenshot({path:"output/playwright/sharing-home-mobile-light.png"});
  assert(errors.length===0,"Browser JS errors: "+errors.join(","));
  console.log(JSON.stringify({flow:"connect-answer-confirm-search-download-refresh-disconnect",isolation,keyNotPersisted:noKey,jsErrors:errors.length}));
}
